server:
  port: 8087

spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/ead_authuser?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true




